version: '3'

networks:
  app-tier:
    driver: bridge

services:
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  app_01:
    image: golang:1.16.6
    networks:
      - app-tier
    depends_on:
      - Etcd
    environment:
      - NODE_NAME=001
    volumes:
       - ./app:/app
    working_dir: /app
    command: bash -c "go get -d -v && go run ./main.go"
